In [53]:
'''To Minimize: Z = -2x1 - 3x2 - 4x3
Subject to: 3x1 + 2x2 + z <= 10
2x1 + 5x2 + 3x3 <= 15
x1, x2, x3 >= 0
'''

import numpy as np

costMatrix = np.matrix([-2, -3, -4])
inequalityConstraintLHS = np.matrix([[3, 2, 1], [2, 5, 3]])
inequalityConstraintRHS = np.matrix([10, 15])
constraint_count = inequalityConstraintRHS.shape[1]

In [61]:
## Problem in standard form
C = np.append(costMatrix, np.zeros((1,constraint_count), dtype = int), axis = 1)
slackVariableIdentity = np.identity(constraint_count, dtype = int)
A = np.append(inequalityConstraintLHS, slackVariableIdentity, axis = 1)
b = inequalityConstraintRHS.reshape(2,1)
A

matrix([[3, 2, 1, 1, 0],
        [2, 5, 3, 0, 1]])

In [66]:
## Solution Matrices
variableCount = C.shape[1]
B_index = np.random.choice(range(variableCount), constraint_count, replace = False)
B = A[:, B_index]
N = np.delete(A, B_index, axis = 1)
B

matrix([[1, 0],
        [3, 1]])

In [70]:
x = np.invert(B)*b
x

matrix([[-35],
        [-70]])